export { default as Info } from './Info.svelte';
export { default as Entradas } from './Entradas.svelte';
export { default as Breadcrumbs } from './Breadcrumbs.svelte';
export { default as Steps } from './Steps.svelte';
export { default as Zonas } from './Zonas.svelte';
export { default as Counter } from './Counter.svelte';
export { default as Resumen } from './Resumen.svelte';
export { default as Barinputer } from './Barinputer.svelte';
export { default as FormasPago } from './FormasPago.svelte';
export { default as Boxlegend } from './Boxlegend.svelte';
export { default as Regalo } from './Regalo.svelte';
export { default as Counterbox} from './Counterbox.svelte';
export { default as Descuento} from './Descuento.svelte';
export { default as Total} from './Total.svelte';
export { default as Counterd} from './Counterd.svelte';